max_frames: 300
max_epoch: 20
batch_size: 80
margin: 0.2

eval_frames: 400
augment: True

## Training details
trainfunc: track1_td-sv

scale: 30

lr_decay: 0.95

pretrained_model_path: WavLM-Base+.pt
weight_finetuning_reg: 0.01
LLRD_factor: 1
LR_Transformer: 2e-5
LR_MHFA: 5e-3

## Loss functions
nClasses: 14377

## Load and save
save_path: exp/Track1_TD-SV

## Model definition
model: wavLM_classifer

nOut: 256
port: 6754
